- name: Install 'insights-client'
  yum:
    name: insights-client
  become: true

- name: Register 'Insights Client'
  insights_register:
    state: present
  become: true
  
- name: Change permissions of Insights Config directory so that Insights System ID can be read
  file:
    path: /etc/insights-client
    mode: og=rx
  become: true

- name: Change permissions of machine_id file so that Insights System ID can be read
  file:
    path: /etc/insights-client/machine-id
    mode: og=r
  become: true

- name: Create directory for ansible custom facts
  file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d
  become: true

- name: Install custom insights fact
  copy:
    src: insights.fact
    dest: /etc/ansible/facts.d
    mode: a+x
  become: true
